# AppLite-Convert: Docker Compose configuration (compatible with both Docker and Podman)
# Use with: docker-compose up --build
# Or with Podman: podman-compose up --build
version: '3.8'

services:
  unstructured-io:
    image: downloads.unstructured.io/unstructured-io/unstructured-api:latest
    environment:
      - PORT=8000
    networks:
      - app-network

  libreoffice:
    image: docker.io/libreofficedocker/libreoffice-unoserver:3.19
    environment:
      - UNOSERVER_STOP_AFTER=50
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - app-network

  pandoc:
    build: ./pandoc-service
    networks:
      - app-network

  gotenberg:
    image: gotenberg/gotenberg:latest
    ports:
      - "4000:3000"
    command:
      - "gotenberg"
      - "--api-port=3000"
      - "--chromium-disable-web-security"
      - "--chromium-allow-file-access-from-files"
    networks:
      - app-network

  proxy:
    build: ./proxy-service
    ports:
      - "${APPLITE_CONVERT_PORT:-8369}:8369"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge