# AppLite-Convert: Docker Compose configuration (compatible with both Docker and Podman)
# Use with: docker-compose up --build
# Or with Podman: podman-compose up --build

services:
  unstructured-io:
    image: downloads.unstructured.io/unstructured-io/unstructured-api:latest
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    networks:
      - app-network

  libreoffice:
    image: docker.io/libreofficedocker/libreoffice-unoserver:3.19
    ports:
      - "2004:2004"
    environment:
      - UNOSERVER_STOP_AFTER=50
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - app-network

  pandoc:
    build: ./pandoc-service
    ports:
      - "3030:3000"
    networks:
      - app-network

  gotenberg:
    image: gotenberg/gotenberg:latest
    ports:
      - "3001:3000"
    command:
      - "gotenberg"
      - "--api-port=3000"
      - "--chromium-disable-web-security"
      - "--chromium-allow-file-access-from-files"
    networks:
      - app-network

  proxy:
    build: ./proxy-service
    ports:
      - "${APPLITE_CONVERT_PORT:-8369}:8369"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: applite-bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1